update: Bump `dbt` to 0.19.1
Tomme/dbt-athena pull request #15
Opened 2021-04-09 13:17 UTC by mrshu

* Bump the version of `dbt` to 0.19.1

* Bump the version of `pyathena` to `2.2.0`

Signed-off-by: mr.Shu <mr@shu.io>

2021-04-27 15:07 UTC, Tomme requested changes
Thanks for the contribution! If you can resolve the comment I have then rebase your branch to `master` I will run the `make run_tests` again and merge your changing in 👍

2021-04-27 15:07 UTC, Tomme commented on setup.py
> +        "pyathena==2.2.0",
Upgrading to `pyathena` 2.2.0 will likely cause an issue within `connections.py`, specifically [L29](https://github.com/Tomme/dbt-athena/blob/70a91f667c42741b58aa650e47bdf848765df089/dbt/adapters/athena/connections.py#L29).

If you set `work_group` to default to `None` it should then be compatible.

This is due to the following PR [#221](https://github.com/laughingman7743/PyAthena/pull/221) within `pyathena`

2021-04-28 11:23 UTC, mrshu commented
Thanks @Tomme, I believe your comment should be resolved. 

I'll see if I can get the tests to run myself as well but would appreciate if you could try them out.

Thanks!

2021-06-03 11:41 UTC, danfran commented
are there still any issues with this PR?

2021-06-30 15:18 UTC, merged